language: ruby
rvm:
  - 2.3.1
env:
  global:
  - TRAVIS_NODE_VERSION="v7.1.0"
  - GH_REF=github.com/IFRCGo/ifrcgo.github.io
  - DEPLOY_BRANCH=publish
  - TARGET_BRANCH=master
  - secure: OgY2DwQaxxu2nah5rq3XpzODpbdVkG4oxGtf4mgjjZV2pEnsuCqUxU70SA5goabTVWOAw/mY1S9GhKv2xHPOa273fjz6X1ZdlmOb5HopbqOCdQahFYruIaCtcesPo4arG7E0O29Xa9KwVkC+AgTa9ToHkdn6Hrzs8edcqHb3FsqkQfkZJ/kjujU/wVraAkB4SZltZJzJKDUb6lPCQuM6g5TIrg5dXDHrVbccJRcKZMYUGANdhIwqhBbA0dR0i2kmeLYH9q4via3dteVuekQkvqQGO3XSSAraTct6SUyn82xCZicOAYXZCp3EmiontNg3hSW2X6FB3/S0bqfRAT/ZF01OnJtadv3A494ZifuEkivwcmY31oE1mtAjsDBPMBdROu0+WqAzEai1kvvQY5oLM2LfgVYcKFVQrDweqpmvUTVXOuhTGn7Atobc+3WuOr6YFBHy6M38XWz2m8ZajK8GKfndRD+IuptgAPi+/ixQn9Q5+CRSWNq0XknOtLy8IavC/BkMcOL7jHK07F9iPjw7/70nlF8a7OqwrTnorTkgYhSjHbYy5sC8J6NJMzi0ReX60NWIr86EqXPtfqa4SxL6+yCC9t4+3LnFrQuXlVet5gVhzCiv5k5vwWNEiFnFTKBpbYyktxg+fPooKz+5E8WZOraOqan3tBznQRO+WM0C2qU=
cache:
  directories:
  - node_modules
before_install:
  - chmod +x ./.build_scripts/deploy.sh
  - rvm install 2.3.1
before_script:
  - . $HOME/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use $TRAVIS_NODE_VERSION
  - npm install -g bower
  - npm install
  - bower install
script: gulp prod
after_success:
  - "./.build_scripts/deploy.sh"
